apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rahulsh91/argo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
